gudang_mobil/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
]

main/urls.py
from django.urls import path
from main.views import main_data, create_product, show_xml, show_json, show_xml_by_id, show_json_by_id, register_user, login_user, logout_user, edit_product, delete_product

app_name = 'main'

urlpatterns = [
    path('', main_data, name='main_data'),
    path('create-product', create_product, name='create_product'),
    path('xml/', show_xml, name='show_xml'),
    path('json/', show_json, name='show_json'),
    path('xml/<int:id>/', show_xml_by_id, name='show_xml_by_id'),
    path('json/<int:id>/', show_json_by_id, name='show_json_by_id'),
    path('register/', register_user, name='register'), 
    path('login/', login_user, name='login'),
    path('logout/', logout_user, name='logout'),
    path('edit-product/<int:id>', edit_product, name='edit_product'),
    path('delete/<int:id>', delete_product, name='delete_product'),
]

main/models.py
from django.db import models
from django.contrib.auth.models import User

class Product(models.Model):
    name = models.CharField(max_length=255)
    manufacturer = models.CharField(max_length=30, default="")
    year = models.CharField(max_length=10)
    amount = models.PositiveIntegerField()
    price = models.PositiveIntegerField()
    description = models.TextField()
    user = models.ForeignKey(User, on_delete=models.CASCADE)

class Developer(models.Model):
    username = models.CharField(max_length=20, null=True)
    user_class = models.CharField(max_length=20)
    
    

    
    

main/forms.py
from django.forms import ModelForm
from main.models import Product
from django import forms  
from django.contrib.auth.models import User  
from django.contrib.auth.forms import UserCreationForm  
from django.core.exceptions import ValidationError  
from django.forms.fields import EmailField  
from django.forms.forms import Form  

class ProductForm(ModelForm):
    class Meta:
        model = Product
        fields = ["name", "manufacturer", "year", "price", "amount", "description"]

class CustomUserCreationForm(UserCreationForm):  
    username = forms.CharField(label='Username', min_length=5, max_length=150)  
    password1 = forms.CharField(label='Password', widget=forms.PasswordInput)  
    password2 = forms.CharField(label='Password Confirmation', widget=forms.PasswordInput)

    def username_clean(self):  
        username = self.cleaned_data['username'].lower()  
        new = User.objects.filter(username = username)  
        if new.count():  
            raise ValidationError("User Already Exist")  
        return username  
    
    def clean_password2(self):  
        password1 = self.cleaned_data['password1']  
        password2 = self.cleaned_data['password2']  \
        
        if password1 and password2 and password1 != password2:  
            raise ValidationError("Password don't match")  
        
        return password2  
    
    def save(self, commit = True):  
        user = User.objects.create_user(  
            self.cleaned_data['username'],  
            self.cleaned_data['email'],  
            self.cleaned_data['password1']
        )
        
        return user


    

main/views.py
import datetime
from django.shortcuts import render
from django.http import HttpResponseRedirect
from main.forms import ProductForm, CustomUserCreationForm
from django.urls import reverse
from main.models import Product, Developer
from django.http import HttpResponse
from django.core import serializers
from django.shortcuts import redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages 
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required

@login_required(login_url='/login')
def main_data(request):
    products = Product.objects.filter(user=request.user)
    developer = Developer.objects.all()

    data = {
        'username': request.user.username,
        'user_class': 'PBP B',
        'developer': developer,
        'products': products,
        #'last_login': request.COOKIES['last_login'],
    }

    return render(request, "main.html", data)

def create_product(request):
    form = ProductForm(request.POST or None)

    if form.is_valid() and request.method == "POST":
        product = form.save(commit=False)
        product.user = request.user
        product.save()
        return HttpResponseRedirect(reverse('main:main_data'))

    context = {'form': form}
    return render(request, "create_product.html", context)

def show_xml(request):
    data = Product.objects.all()
    return HttpResponse(serializers.serialize("xml", data), content_type="application/xml")

def show_json(request):
    data = Product.objects.all()
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

def show_xml_by_id(request, id):
    data = Product.objects.filter(pk=id)
    return HttpResponse(serializers.serialize("xml", data), content_type="application/xml")

def show_json_by_id(request, id):
    data = Product.objects.filter(pk=id)
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

def register_user(request):
    form = CustomUserCreationForm()

    if request.method == "POST":
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Your account has been successfully created!')
            return redirect('main:login')
    context = {'form':form}
    return render(request, 'register.html', context)

def login_user(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            response = HttpResponseRedirect(reverse("main:main_data")) 
            response.set_cookie('last_login', str(datetime.datetime.now()))
            return response
        else:
            messages.info(request, 'Sorry, incorrect username or password. Please try again.')
    context = {}
    return render(request, 'login.html', context)

def logout_user(request):
    logout(request)
    return redirect('main:login')

def edit_product(request, id):
    product = Product.objects.get(pk = id)
    form = ProductForm(request.POST or None, instance=product)

    if form.is_valid() and request.method == "POST":
        form.save()
        return HttpResponseRedirect(reverse('main:main_data'))

    context = {'form': form}
    return render(request, "edit_product.html", context)

def delete_product(request, id):
    product = Product.objects.get(pk = id)
    product.delete()
    return HttpResponseRedirect(reverse('main:main_data'))

main/templates/create_product.html
{% extends 'base.html' %} 

{% block content %}
<h1>Add New Product</h1>

<form method="POST">
    {% csrf_token %}
    <table>
        {{ form.as_table }}
        <tr>
            <td></td>
            <td>
                <input type="submit" value="Add Product"/>
            </td>
        </tr>
    </table>
</form>

{% endblock %}

main/templates/edit_product.html
{% extends 'base.html' %}

{% load static %}

{% block content %}

<h1>Edit Product</h1>

<form method="POST">
    {% csrf_token %}
    <table>
        {{ form.as_table }}
        <tr>
            <td></td>
            <td>
                <input type="submit" value="Edit Product"/>
            </td>
        </tr>
    </table>
</form>

{% endblock %}

main/templates/login.html
{% extends 'base.html' %}

{% block meta %}
    <title>Login</title>
{% endblock meta %}

{% block content %}
<style>
    body {
        background-color: #f2f2f2;
        display: flex;
        justify-content: center;
        align-items: center;
        height: 100vh;
        margin: 0;
    }

    h1 {
        color: #000000;
        font-family: 'Franklin Gothic Medium', 'Arial Narrow', Arial, sans-serif;
    }

    .login {
        width: 400px;
        height: 300px;
        background-color: #87cee8;
        padding: 40px 50px 40px 50px;
        box-shadow: 2px 2px 5px 5px #000000;
        text-align: center;
        border-radius: 5px;
        
    }

    input.form-control {
        text-align: left;
        width: 200px;
        border-radius: 10px;
    }

    input.btn.login_btn {
        text-align: left;
        background-color: lightgray;
        padding: 5px 8px;
        border-radius: 10px;
        margin-top: 5px;
    }

    .btn.login_btn:hover {
        color: white;
        background-color: #000000;
    }

    td.login_button {
        text-align: left;
    }

    td {
        font-family: Georgia;
        color: #000000;
        
    }

    .register {
        margin-top: 10px;
        margin-left: 30px;
        margin-right: 30px;
    }
</style>
<div class = "login">

    <h1>LOGIN</h1>

    <form method="POST" action="">
        {% csrf_token %}
        <table>
            <tr>
                <td>Username: </td>
                <td><input type="text" name="username" placeholder="Username" class="form-control"></td>
            </tr>
                    
            <tr>
                <td>Password: </td>
                <td><input type="password" name="password" placeholder="Password" class="form-control"></td>
            </tr>

            <tr>
                <td></td>
                <td class="login_button"><input class="btn login_btn" type="submit" value="Login"></td>
            </tr>
        </table>
    </form>

    {% if messages %}
        <ul>
            {% for message in messages %}
                <li>{{ message }}</li>
            {% endfor %}
        </ul>
    {% endif %}     
    
    <div class="register">
        Don't have an account yet? <a href="{% url 'main:register' %}">Register Now</a>
    </div>

</div>

{% endblock content %}

main/templates/main.html
{% extends 'base.html' %}

{% block content %}
    <h1>FBK1NG AutoShop</h1>

    <h5>Name: </h5>
    <p>{{ username }}</p> 
    <h5>Class: </h5>
    <p>{{ user_class }}</p>
    

    <table>
        <tr>
            <th>Name</th>
            <th>Manufacturer</th>
            <th>Year</th>
            <th>Price</th>
            <th>Amount</th>
            <th>Description</th>
        </tr>
    
        {% for product in products %}
            <tr>
                <td>{{product.name}}</td>
                <td>{{product.manufacturer}}</td>
                <td>{{product.year}}</td>
                <td>{{product.price}}</td>
                <td>{{product.amount}}</td>
                <td>{{product.description}}</td>
                <td>
                    <a href="{% url 'main:edit_product' product.pk %}">
                        <button>
                            Edit
                        </button>
                    </a>
                    <a href="{% url 'main:delete_product' product.pk %}">
                        <button>
                            Delete
                        </button>
                    </a>
                </td>

            </tr>
        {% endfor %}
    </table>
    
    <br />

    <h5>Sesi terakhir login: {{ last_login }}</h5>
    
    <a href="{% url 'main:create_product' %}">
        <button>
            Add New Product
        </button>
    </a>

    <a href="{% url 'main:logout' %}">
        <button>
            Logout
        </button>
    </a>
{% endblock content %}

main/templates/register.html
{% extends 'base.html' %}

{% block meta %}
    <title>Register</title>
{% endblock meta %}

{% block content %}  
<style>
    body {
        background-color: #f2f2f2;
        display: flex;
        justify-content: center;
        align-items: center;
        height: 100vh;
        margin: 0;
    }

    .login {
        background-color: #87cee8 ;
        height: 300px;
        width: 500px;
        text-align: center;
        padding: 40px 50px 40px 50px;
        box-shadow: 2px 2px 5px 5px #000000;
        border-radius: 5px;
    }

    .helptext {
        visibility: hidden;
    }
    
    h1 {
        color: #000000;
        font-family: 'Franklin Gothic Medium', 'Arial Narrow', Arial, sans-serif;
        text-align: center;
        margin-bottom: 15px;
    }

    .register_btn {
        text-align: center;
        font-family: Georgia;
        border-radius: 10px;
        background-color: lightgray;
        padding: 4px 7px;
        margin-top: 5px;
    }

    td.register {
        text-align: left;
    }

    .register_btn:hover {
        background-color: #000000;
        color: white;
    }
    
</style>

<div class = "login">
    
    <h1>REGISTER</h1>  

        <form method="POST">  
            {% csrf_token %}  
            <table>  
                {{ form.as_table }}  
                <tr>  
                    <td></td>
                    <td class="register"><input class="register_btn" type="submit" name="submit" value="Daftar"/></td>  
                </tr>  
            </table>  
        </form>

    {% if messages %}  
        <ul>   
            {% for message in messages %}  
                <li>{{ message }}</li>  
                {% endfor %}  
        </ul>   
    {% endif %}

</div>  

{% endblock content %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8" />
        <meta
            name="viewport"
            content="width=device-width, initial-scale=1.0"
        />
        {% block meta %}
            <meta charset="UTF-8" />
            <meta name="viewport" content="width=device-width, initial-scale=1">
        {% endblock meta %}
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
        <script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha384-KyZXEAg3QhqLMpG8r+J4jsl5c9zdLKaUk5Ae5f5b1bw6AUn5f5v8FZJoMxm6f5cH1" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.min.js" integrity="sha384-BBtl+eGJRgqQAUMxJ7pMwbEyER4l1g+O15P+16Ep7Q9Q+zqX6gSbd85u4mG4QzX+" crossorigin="anonymous"></script>
    </head>

    <body>
        {% block content %}
        {% endblock content %}
    </body>
</html>